#!/usr/bin/env bash
#
# Container entrypoint.
#
# Responsibilities, in order:
#   1. reconcile the container user with the caller's PUID/PGID (NAS users are
#      rarely uid 1000),
#   2. give the unprivileged user ownership of the two OpenCode volumes and the
#      in-image project directory,
#   3. in `plugin-inject` prompt mode, materialise the no-op backend plugin and
#      the opencode.json that points at it,
#   4. drop privileges and exec the real command, so signals and the exit code
#      belong to the process that matters.
#
# Environment: PUID, PGID (numeric ids, default to the `node` account's ids),
# OPENCODE_PROXY_PROMPT_MODE (standard|plugin-inject).

set -euo pipefail

readonly APP_USER="node"
readonly DATA_DIR="/home/node/.local/share/opencode"
readonly STATE_DIR="/home/node/.local/state"
readonly CONFIG_DIR="/home/node/.config/opencode"
readonly PROJECT_DIR="/home/node/project"
readonly EMPTY_PLUGIN_DIR="${CONFIG_DIR}/plugin/opencode-gateway-empty"

log() {
    printf '[entrypoint] %s\n' "$*" >&2
}

fail() {
    printf '[entrypoint] error: %s\n' "$*" >&2
    exit 1
}

# Reject ids that would make groupmod/usermod fail with a cryptic message.
require_numeric_id() {
    local label="$1" value="$2"
    case "$value" in
        '' | *[!0-9]*) fail "${label} must be a numeric user/group id, got '${value}'" ;;
    esac
}

if [[ $# -eq 0 ]]; then
    fail "no command given; the image expects e.g. \`node index.js\`"
fi

# Running with `--user` means there is nothing to reconcile — respect it.
if [[ "$(id -u)" -ne 0 ]]; then
    log "not running as root: skipping PUID/PGID reconciliation"
    exec "$@"
fi

current_uid="$(id -u "$APP_USER")"
current_gid="$(id -g "$APP_USER")"
target_uid="${PUID:-$current_uid}"
target_gid="${PGID:-$current_gid}"
require_numeric_id PUID "$target_uid"
require_numeric_id PGID "$target_gid"

if [[ "$target_gid" != "$current_gid" ]]; then
    log "remapping group ${APP_USER}: ${current_gid} -> ${target_gid}"
    groupmod --non-unique --gid "$target_gid" "$APP_USER"
fi

if [[ "$target_uid" != "$current_uid" ]]; then
    log "remapping user ${APP_USER}: ${current_uid} -> ${target_uid}"
    usermod --non-unique --uid "$target_uid" "$APP_USER"
fi

mkdir -p "$DATA_DIR" "$STATE_DIR" "$CONFIG_DIR"

# Named volumes are created as root on first use, so ownership is fixed up here
# rather than in the image. Chowning the *parents* (`/home/node/.local`,
# `/home/node/.config`) also covers the case where a volume replaced a directory
# the image shipped; -R keeps working when the host pre-populated them.
if ! chown -R "${APP_USER}:${APP_USER}" \
    /home/node/.local \
    /home/node/.config \
    "$PROJECT_DIR"; then
    fail "cannot give ${APP_USER} ownership of the OpenCode volumes"
fi

if [[ "${OPENCODE_PROXY_PROMPT_MODE:-standard}" == "plugin-inject" ]]; then
    log "prompt mode 'plugin-inject': installing the empty backend plugin"
    install -d -o "$APP_USER" -g "$APP_USER" "$EMPTY_PLUGIN_DIR"

    cat >"${EMPTY_PLUGIN_DIR}/index.js" <<'PLUGIN'
// Generated by the container entrypoint for OPENCODE_PROXY_PROMPT_MODE=plugin-inject.
// The gateway builds the prompt itself, so the backend plugin stays a no-op.
export const opencodeGatewayEmptyPlugin = async () => ({});
export default opencodeGatewayEmptyPlugin;
PLUGIN

    cat >"${CONFIG_DIR}/opencode.json" <<CONFIG
{
    "plugin": ["${EMPTY_PLUGIN_DIR}/index.js"],
    "instructions": [],
    "theme": "system"
}
CONFIG

    chown -R "${APP_USER}:${APP_USER}" "$CONFIG_DIR"
fi

command -v gosu >/dev/null 2>&1 ||
    fail "gosu is not installed in the image; cannot drop privileges to ${APP_USER}"

log "starting as ${APP_USER} (${target_uid}:${target_gid}): $*"
exec gosu "$APP_USER" "$@"
